### ISSUE TITLE
Question: Why is save_order False by default?

### ISSUE THREAD

**Issue by jdevera** [un33k/python-slugify#118]
I was trying to understand the meaning of save_order better and I see that it can skip some long words when they will not fit whole within max_length. I'm very curious about why this is the default behaviour.

**Comment by un33k** [comment]
Things have been added over years.  Have a look at the code, for the behavior, especially where the params are passed in, we have description of each args.

**Comment by jdevera** [comment]
I played around with it enough to understand what it does, and it seemed "interesting" to have a feature but I was surprised it was default behaviour.

**Comment by un33k** [comment]
Evolving software sometimes start with things that don't make sense many years later.  Minimally we have ability to on/off things.

**Comment by un33k** [comment]
This is **Dojo**, posting a maintainer-authorized follow-up linking this issue to https://github.com/un33k/python-slugify/pull/191.

save_order remains False by default to preserve existing outputs. The behavior is documented rather than silently changing the default.

The default algorithm remains legacy; improved output rules are opt-in. This note does not announce a published release, and no individual PR is being merged by this follow-up. Thank you for the contribution and discussion.

🚀 Generated with [Dojo](https://heydojo.ai) ⛩️
