### ISSUE TITLE
Setup.py dependency checker does not work for pip

### ISSUE THREAD

**Issue by bolkedebruin** [un33k/python-slugify#70]
Hi,

Unfortunately the check for text-unidecode (https://github.com/un33k/python-slugify/pull/63) does not work with pip. Pip executes installations in an isolated environment and does not support `setup_requires`, hence it cannot detect if text-unidecode is installed when text-unidecode was used in install_requires and not installed beforehand.

Honestly it seems that this is just very hard or impossible to do in Python land. So, what we probably will do is to put slugify in a vendor location and make it dependent on text-unidecode.

Just opening this to see if you would have other suggestions or ideas.

Cheers

**Comment by un33k** [comment]
@bolkedebruin I have tested it and it works. Please provide exact env to reproduce this. 

OS, version
pip version 
python version

**Comment by insysion** [comment]
@un33k We're getting the a similar problem within (and only within) a `pipenv lock` process (and only on a specific machine!). It's proving a nightmare to debug. No doubt this is not due to any bug on your part but rather the interplay of many factors.

It could, however, be solved if you were using a more standard installation paradigm. I understand why you rejected the `extras_require` approach of https://github.com/un33k/python-slugify/issues/68. But what if `text-unidecode` were the default and *always required* backend?

It's a tiny-package with a permissive license. It's hard to see any users of `slugify[unidecode]` objecting to having it installed redundantly. Whereas the ramifications of incidentally installing `unidecode` by accident are quite serious for a business.

Happy to raise a PR if that's an approach you'd endorse.

**Comment by insysion** [comment]
...and I've just seen https://github.com/un33k/python-slugify/pull/72 colour me very happy :)

**Comment by un33k** [comment]
Version 3.0 promotes `text-unidecode` to primary decoding api.  https://github.com/un33k/python-slugify/pull/73
